### ISSUE TITLE
How to selected Cell, and let him set-top focused on location?

### ISSUE THREAD

**Issue by xhzengAIB** [izotx/JMCMarchingAnts#1]
Hello @izotx 

When i selected same Cell, like this code. not focused location at Cell.

``` objc
- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath {
    [collectionView selectItemAtIndexPath:indexPath animated:YES scrollPosition:UICollectionViewScrollPositionTop];
}
```

Jack

**Comment by gulfcoastdev** [comment]
I don't understand your problem.

**Comment by xhzengAIB** [comment]
Look like this gif. 

![hello](https://cloud.githubusercontent.com/assets/1969908/11179384/df3922d2-8c8d-11e5-8d0a-231890f3c5b8.gif)

When i selected second cell，The scroll offset is error.

Jack

**Comment by gulfcoastdev** [comment]
I don't see how it's related to my library.

**Comment by xhzengAIB** [comment]
I'm very sorry
